"""version 1.1

Revision ID: c50004780dce
Revises: 779ddef580fa
Create Date: 2017-10-31 02:44:16.340580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50004780dce'
down_revision = '779ddef580fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_pitch_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'pitch_id')
    op.add_column('pitches', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'category_id')
    op.add_column('categories', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_pitch_id_fkey', 'categories', 'pitches', ['pitch_id'], ['id'])
    # ### end Alembic commands ###
