"""version 1.1.2

Revision ID: ca7387243aa3
Revises: 823ed633561e
Create Date: 2017-10-31 16:17:12.869522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7387243aa3'
down_revision = '823ed633561e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('author', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
